In [1]:
import torch
import uproot
import numpy as np
import matplotlib.pyplot as plt

In [2]:
fp = '/srv01/agrp/nilotpal/projects/glow_atlas/hepattn/src/hepattn/experiments/atlas/logcrash_bf16/losses_per_element_20260203_153807.pt'
data = torch.load(fp)

In [3]:
keys1 = list(data.keys())
for k in keys1:
    print(k)
    keys2 = list(data[k].keys())

    for kk in keys2:
        keys3 = list(data[k][kk].keys())
        print(f"  {kk}")

        for kkk in keys3:
            print(f"    {kkk}")
            t = data[k][kk][kkk]
            print(f"      => {t.shape}")

            if len(t.shape) == 2:
                flat_idx = t.reshape(-1).argmax()
                rt, ct = torch.unravel_index(flat_idx, t.shape)
                print(f"      => ({rt}, {ct})")
            else:
                print(f"      => {t.argmax()}")

            print(f"      => {t.max()}")
            print()

layer_0
  classification
    object_ce
      => torch.Size([128, 128])
      => (63, 5)
      => 81.5

  mask
    mask_bce
      => torch.Size([128, 500])
      => (118, 83)
      => 2144814.75

    mask_dice
      => torch.Size([128, 500])
      => (75, 197)
      => 0.9444708228111267

layer_1
  classification
    object_ce
      => torch.Size([128, 128])
      => (63, 5)
      => 52.25

  mask
    mask_bce
      => torch.Size([128, 500])
      => (118, 77)
      => 133.8387451171875

    mask_dice
      => torch.Size([128, 500])
      => (75, 197)
      => 0.9444500803947449

layer_2
  classification
    object_ce
      => torch.Size([128, 128])
      => (63, 5)
      => 35.25

  mask
    mask_bce
      => torch.Size([128, 500])
      => (118, 97)
      => 752.7410888671875

    mask_dice
      => torch.Size([128, 500])
      => (75, 197)
      => 0.9444462060928345

layer_3
  classification
    object_ce
      => torch.Size([128, 128])
      => (63, 5)
      => 35.25

  mask
    ma

In [4]:
getitem_idxs = [
    3350063, 17792569, 12225342, 17147743, 18148566, 18024054, 18050509, 10616122, 2662331, 
    736358, 738161, 6301338, 6040897, 10781297, 17583004, 9560948, 1211960, 17714297, 14758220, 
    670923, 4107818, 7065564, 3597052, 11738625, 7517874, 12635832, 11774898, 8124478, 3441336, 
    11985788, 14192159, 8923273, 12160217, 4637771, 3953803, 17447389, 17551773, 11368207, 3480115, 
    16497994, 13446963, 2910783, 6891705, 7063453, 5912210, 4421846, 8918433, 12446957, 6448892, 
    11869733, 1888567, 4610040, 13622349, 9851939, 2752342, 9894208, 16992183, 5837215, 1954224, 
    3391824, 6085564, 10707666, 663302, 7022611, 1792871, 16291165, 7510504, 2696647, 9924618, 
    18109412, 11568237, 16653663, 13640695, 7584732, 18087817, 6166516, 17018284, 10163873, 6249678, 
    822283, 15441923, 9760974, 7538377, 4147491, 12682878, 2015442, 10202062, 14332365, 9555096, 
    4871794, 14582639, 8550040, 2544078, 17745896, 17170514, 13714892, 8186445, 14821857, 2400385, 
    2851888, 10642865, 15209135, 17548680, 15235229, 11744009, 10867036, 2481040, 16257370, 11167007, 
    5868241, 15365455, 5628674, 9336345, 4286662, 5458419, 9374858, 15193856, 13678932, 8614747,
    9643340, 13638892, 1728010, 4077352, 9880717, 11081621, 10044827, 16398204, 11502956
]

In [5]:
getitem_idxs[118]

8614747

In [6]:
tree = uproot.open('/storage/agrp/dreyet/FullEventReco/HGPflow_ATLAS/data/dijet_JZ1_to_JZ8_Jan2026/train_1M/train_jz123.root')['EventTree']

In [7]:
nparticles = tree['nparticle'].array(library='np')

np_filtered = nparticles[nparticles <= 127]
print(len(np_filtered) + 41 - len(nparticles))

print(np.arange(len(nparticles))[nparticles <= 127][8614747])

0
8614747


In [8]:
track_variables = [
    "track_pt",
    "track_eta",
    "track_phi",
    "track_d0",
    "track_z0",
    "track_eta_int",
    "track_phi_int",
]

topo_variables = [
    "topo_e",
    "topo_pt",
    "topo_eta",
    "topo_phi",
    "topo_num_cells",
    "topo_em_frac",
    "topo_center_mag",
    "topo_center_lambda",
]

particle_variables = [
    "particle_e",
    "particle_pt",
    "particle_eta",
    "particle_phi",
    "particle_pdgid",
]

aux_vars = [
    "particle_track_idx",
    "track_particle_idx",
    "topo2particle_topo_idx",
    "topo2particle_particle_idx",
    "topo2particle_energy",
    "eventNumber",
]

In [9]:
data_array = tree.arrays(
    track_variables + topo_variables + particle_variables + aux_vars, 
    library="np",
    entry_start=8614747,
    entry_stop=8614748
)

In [10]:
np.set_printoptions(precision=2, suppress=True)

for k, v in data_array.items():
    print(f"{k}") 
    print(f'   {v[0]}\n')

track_pt
   [1.54 3.37 0.74]

track_eta
   [-0.43 -0.55 -0.92]

track_phi
   [ 1.74  2.56 -2.97]

track_d0
   [-0.02 -0.03 -0.25]

track_z0
   [83.1  83.05 83.06]

track_eta_int
   [-0.39 -0.51 -0.94]

track_phi_int
   [2.03 2.43 2.69]

topo_e
   [2.71 2.3  0.78 0.31 0.27 0.27 0.19 0.2 ]

topo_pt
   [2.29 2.04 0.72 0.3  0.26 0.24 0.16 0.16]

topo_eta
   [-0.59 -0.49 -0.41 -0.21 -0.28 -0.51 -0.57 -0.72]

topo_phi
   [2.7  2.43 2.07 2.41 2.51 2.01 2.44 2.71]

topo_num_cells
   [42 69 29 13 14 14 12 32]

topo_em_frac
   [0.89 0.16 0.04 0.78 0.26 0.8  0.   0.79]

topo_center_mag
   [1931.53 1877.58 1886.19 1659.17 1658.92 1804.57 2276.32 2044.54]

topo_center_lambda
   [158.57 188.77 258.18 127.35 101.96 113.88 529.93 134.99]

particle_e
   [4.94 0.95 1.08 0.28 1.21 0.01 1.46 1.95 3.96 0.53 2.98]

particle_pt
   [0.76 0.83 0.37 0.27 0.76 0.   1.42 1.56 3.42 0.4  2.47]

particle_eta
   [-2.54 -0.55 -1.71 -0.27 -0.92  1.45 -0.22 -0.43 -0.55 -0.77 -0.64]

particle_phi
   [-1.42  1.98 -0.15  2

In [11]:
num_objects = 128


def get_incidence(data_array, idx, num_objects):
    n_tracks = len(data_array["track_pt"][0])
    n_particles = len(data_array["particle_pt"][0])
    n_nodes = len(data_array["track_pt"][0]) + len(data_array["topo_e"][0])

    incidence_matrix = np.zeros((num_objects, n_nodes))

    part_idx = data_array["track_particle_idx"][idx]
    track_idx = np.arange(len(part_idx))
    incidence_matrix[part_idx, track_idx] = 1.0

    topo_idx = data_array["topo2particle_topo_idx"][idx]
    part_idx = data_array["topo2particle_particle_idx"][idx]
    incidence_matrix[part_idx, topo_idx + n_tracks] = data_array["topo2particle_energy"][idx]

    # check for TC w/o associated particles
    if (incidence_matrix.sum(axis=0) == 0).any():
        noisy_cols = np.where(incidence_matrix.sum(axis=0) == 0)[0]
        fake_rows = np.arange(len(noisy_cols)) + n_particles
        if not (fake_rows < num_objects).all():
            print(f"Warning: fake_rows go beyond maximum ({num_objects}) particles. Dropping them!")
            noisy_cols = noisy_cols[fake_rows < num_objects]
            fake_rows = fake_rows[fake_rows < num_objects]
        incidence_matrix[fake_rows, noisy_cols] = 1.0

    # normalize
    incidence_matrix /= np.clip(incidence_matrix.sum(axis=0, keepdims=True), a_min=1e-6, a_max=None)

    incidence = torch.tensor(incidence_matrix, dtype=torch.float32)

    # incidence = torch.nn.functional.pad(incidence, (0, self.max_nodes - n_nodes, 0, 0))
    return incidence

In [12]:
inc0 = get_incidence(data_array, idx=0, num_objects=num_objects)

In [13]:
torch.set_printoptions(precision=4, sci_mode=False, threshold=100000, linewidth=200)
zero_mask = inc0.sum(axis=1) == 0

print('incidence:')
print(inc0[~zero_mask])

inc_mask = inc0[~zero_mask] > 0.01
print('\nmask:')
print(inc_mask.float())

print('\nnonzero fraction:', inc_mask.float().mean().item())

incidence:
tensor([[    0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0005],
        [    0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0059,     0.0000,     0.0000,     0.9950,     0.0000,     0.0000],
        [    0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0011,     0.0000,     0.0000,     0.0000],
        [    0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.9736,     0.0000,     0.0000,     0.0000,     0.0000],
        [    0.0000,     0.0000,     1.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0200],
        [    0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0116,     0.0000,     0.0000,     0.0000,     0.0000],
        [    0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.9989,     0.0000,     0.0000,     0.00

In [15]:
inc0.shape

torch.Size([128, 11])